<?php

namespace App\Models;

use App\Observers\MenuObserver;

/**
 * App\Models\Menu
 *
 * @property int $id
 * @property string $name 菜单名称
 * @property string $icon 菜单图标
 * @property int $parent_id 父级菜单ID
 * @property string $url 菜单链接
 * @property int $status 状态 1显示 2隐藏
 * @property int $sort 排序
 * @property string|null $content 描述
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\MenuModel newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\MenuModel newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\MenuModel query()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\MenuModel whereContent($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\MenuModel whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\MenuModel whereIcon($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\MenuModel whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\MenuModel whereName($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\MenuModel whereParentId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\MenuModel whereSort($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\MenuModel whereStatus($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\MenuModel whereUpdatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\MenuModel whereUrl($value)
 * @mixin \Eloquent
 * @property string|null $icons 菜单图标
 * @property-read \App\Models\PermissionsModel|null $permissions
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\MenuModel whereIcons($value)
 */
class MenuModel extends BaseModel
{
    protected $fillable = ['parent_id', 'name', 'url', 'icons', 'sort', 'status', 'content'];

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

    }

    /**
     * 关联permissions表
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function permissions()
    {
        return $this->hasOne(PermissionsModel::class, 'mid', 'id');
    }

    /**
     * 获取父级菜单
     * @param int $parent_id
     * @return array
     */
    public static function parentMenu($parent_id = 0)
    {
        $menuTableList = MenuModel::orderBy("sort")->get()->toArray();
        return getTreeArray($menuTableList, $parent_id, 2);
    }
}
